on: push
name: Build and deploy on push
jobs:
  build:
    name: shalzz/zola-deploy-action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: 'custom deply'
      uses: './.github/action/'
      env:
        PAGES_BRANCH: gh-pages
        BUILD_THEMES: false
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
